apiVersion: skaffold/v4beta13
kind: Config
metadata:
  name: bingeo-base-infra

manifests:
  rawYaml:
    - ./k8s/base/*

deploy:
  kubectl: {}

---
apiVersion: skaffold/v4beta13
kind: Config
metadata:
  name: bingeo-infra-networking

manifests:
  rawYaml:
    - ./k8s/networking/*

deploy:
  kubectl: {}

---
apiVersion: skaffold/v4beta13
kind: Config
metadata:
  name: bingeo-observability

manifests:
  rawYaml:
    - ./observability/**/*

deploy:
  kubectl: {}

---
apiVersion: skaffold/v4beta13
kind: Config
metadata:
  name: bingeo-doppler-secrets

manifests:
  rawYaml:
    - ./k8s/doppler/templates/*

deploy:
  kubectl: {}

---
apiVersion: skaffold/v4beta13
kind: Config
metadata:
  name: bingeo-full

requires:
  - configs: ["bingeo-base-infra"]
  - configs: ["bingeo-identity-cfg"]
    path: ../services/bingeo-identity-service
  - configs: ["bingeo-payment-cfg"]
    path: ../services/bingeo-payment-service
  - configs: ["bingeo-content-cfg"]
    path: ../services/bingeo-content-service
  - configs: ["bingeo-streaming-cfg"]
    path: ../services/bingeo-streaming-service
  - configs: ["bingeo-infra-networking"]

deploy:
  kubectl: {}

---
apiVersion: skaffold/v4beta13
kind: Config
metadata:
  name: bingeo-full-obs

requires:
  - configs: ["bingeo-full"]
  - configs: ["bingeo-observability"]

deploy:
  kubectl: {}
