# Bingeo Namespaces
---
apiVersion: v1
kind: Namespace
metadata:
  name: bingeo-app
  labels:
    name: bingeo-app
    part-of: bingeo
---
apiVersion: v1
kind: Namespace
metadata:
  name: bingeo-obs
  labels:
    name: bingeo-obs
    part-of: bingeo
---
apiVersion: v1
kind: Namespace
metadata:
  name: bingeo-envoy-gateway
  labels:
    name: bingeo-envoy-gateway
    part-of: bingeo
